/**
 * CricClubs API client for Belgium Cricket
 *
 * The `x-content-token` is a time-based token generated by CricClubs' JS.
 * Strategy:
 *   1. Use Playwright to navigate to CricClubs; capture the token from request headers.
 *   2. Reuse that token for direct axios calls for ~40 seconds (token TTL ~60s).
 *   3. Fall back to navigation-based interception when token expires.
 */

const axios    = require('axios');
const { chromium } = require('playwright');

const LEAGUE_ID = 'j-x9YyxrIre5Zj_OS9HQyA';
const API_BASE  = 'https://core-prod-origin.cricclubs.com/core/public';
const API_V     = '4.0.536';
const SITE      = 'https://cricclubs.com/CricketBelgium';

// ── Token management ──────────────────────────────────────────────
let _token   = null;
let _tokenTs = 0;
const TOKEN_VALID_MS = 90 * 1000; // 90s (token TTL is ~60s but we capture it early)

let _browser = null;
let _page    = null;
let _ready   = false;
let _initP   = null;

// ── Navigation mutex (only one page.goto at a time) ───────────────
let _navQueue = Promise.resolve();

async function ensureBrowser() {
  if (_ready && _page) return;
  if (_initP) return _initP;
  _initP = _launchBrowser().finally(() => { _initP = null; });
  return _initP;
}

async function _launchBrowser() {
  if (_browser && _browser.isConnected()) return;
  console.log('  🌐 Launching browser…');
  _browser = await chromium.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox',
           '--disable-blink-features=AutomationControlled'],
  });
  const ctx = await _browser.newContext({
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
    viewport: { width: 1280, height: 900 },
    locale: 'en-US',
    serviceWorkers: 'block',  // prevent SW caching from hiding API calls
  });
  _page = await ctx.newPage();
  await _page.addInitScript(() => {
    Object.defineProperty(navigator, 'webdriver', { get: () => false });
    // Patch XHR + fetch to capture x-content-token into window.__xct
    const _save = (h) => { if (h) window.__xct = h; };
    const _origSetRH = XMLHttpRequest.prototype.setRequestHeader;
    XMLHttpRequest.prototype.setRequestHeader = function(n, v) {
      if (n && n.toLowerCase() === 'x-content-token') _save(v);
      return _origSetRH.apply(this, arguments);
    };
    const _origFetch = window.fetch;
    window.fetch = function(input, init = {}) {
      try {
        const h = init.headers;
        const tok = h instanceof Headers ? h.get('x-content-token')
                  : h ? (h['x-content-token'] || h['X-Content-Token']) : null;
        if (tok) _save(tok);
      } catch(_) {}
      return _origFetch.apply(this, arguments);
    };
  });

  // Capture token from all outgoing requests
  await _page.route('**/core-prod-origin.cricclubs.com/**', async route => {
    const tok = route.request().headers()['x-content-token'];
    if (tok) { _token = tok; _tokenTs = Date.now(); }
    await route.continue();
  });

  // Load CricClubs to initialise the session
  await _page.goto(`${SITE}/series-list?leagueId=${LEAGUE_ID}`, {
    waitUntil: 'networkidle', timeout: 45000,
  });
  _ready = true;
  console.log('  ✅ Browser ready');
}

/** Check if we have a fresh token */
function tokenFresh() {
  return _token && (Date.now() - _tokenTs < TOKEN_VALID_MS);
}

/** Refresh token by navigating to series-list — queued so it doesn't conflict */
function refreshToken() {
  const result = _navQueue.then(() => _refreshTokenImpl());
  _navQueue = result.then(() => {}, () => {});
  return result;
}

async function _refreshTokenImpl() {
  console.log('  🔄 Refreshing token via navigation…');
  _token = null;
  await _page.goto(`${SITE}/series-list?leagueId=${LEAGUE_ID}`, {
    waitUntil: 'networkidle', timeout: 30000,
  }).catch(() => {});
  // Try window.__xct first (injected by addInitScript patch)
  const winTok = await _page.evaluate(() => window.__xct).catch(() => null);
  if (winTok) { _token = winTok; _tokenTs = Date.now(); }
  // Also poll for route-interceptor capture
  for (let i = 0; i < 20 && !_token; i++) {
    await _page.waitForTimeout(300);
  }
  if (_token) console.log('  ✅ Token refreshed');
  else console.warn('  ⚠️  Token still missing after navigation');
}

/** Make a direct API call using the captured token */
async function directCall(endpoint, params = {}, _retry = false) {
  await ensureBrowser();
  if (!tokenFresh()) {
    await refreshToken();
  }
  if (!_token) throw new Error('No token available');

  const url = `${API_BASE}/${endpoint}`;
  let resp;
  try {
    resp = await axios.get(url, {
      params: { v: API_V, ...params },
      headers: {
        'x-content-token': _token,
        'Accept': 'application/json',
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/124.0.0.0 Safari/537.36',
        'Referer': 'https://cricclubs.com/',
        'Origin': 'https://cricclubs.com',
      },
      timeout: 15000,
    });
  } catch (e) {
    // 4xx from CricClubs — try one token refresh then retry
    if (!_retry && e.response?.status) {
      console.log(`  ⚠️  API ${e.response.status} on ${endpoint}, refreshing token…`);
      await refreshToken();
      return directCall(endpoint, params, true);
    }
    throw e;
  }

  if (resp.data?.errorCode === 'SEC001') {
    if (_retry) throw new Error('SEC001 after token refresh');
    console.log('  ⚠️  SEC001, refreshing token…');
    await refreshToken();
    return directCall(endpoint, params, true);
  }

  return resp.data;
}

/** Navigate to a page and capture the first API response matching urlPattern.
 *  Optionally also requires urlMustContain to be present in the response URL.
 *  Serialized via _navQueue so only one navigation runs at a time. */
function captureViaNav(pagePath, urlPattern, extraWait = 1500, urlMustContain = null) {
  // Chain onto the existing queue so navigations run one at a time
  const result = _navQueue.then(() => ensureBrowser()).then(() => _captureViaNavImpl(pagePath, urlPattern, extraWait, urlMustContain));
  // Update queue: wait for this navigation (suppress errors so next caller isn't blocked)
  _navQueue = result.then(() => {}, () => {});
  return result;
}

async function _captureViaNavImpl(pagePath, urlPattern, extraWait, urlMustContain) {
  return new Promise(async (resolve) => {
    let settled = false;
    const settle = (val) => { if (!settled) { settled = true; resolve(val); } };

    const timeout = setTimeout(() => settle(null), 25000);

    const handler = async (response) => {
      if (!response.url().includes(urlPattern)) return;
      if (urlMustContain && !response.url().includes(urlMustContain)) {
        console.log(`  ⏭️  Skipping [${urlPattern}] — URL missing "${urlMustContain}": ${response.url()}`);
        return;
      }
      try {
        const data = await response.json();
        console.log(`  📡 Captured [${urlPattern}] from URL: ${response.url()}`);
        clearTimeout(timeout);
        _page.off('response', handler);
        // Also try to harvest token from window.__xct
        _page.evaluate(() => window.__xct).then(tok => {
          if (tok) { _token = tok; _tokenTs = Date.now(); }
        }).catch(() => {});
        settle(data);
      } catch (_) {}
    };

    _page.on('response', handler);

    await _page.goto(`${SITE}/${pagePath}`, {
      waitUntil: 'networkidle', timeout: 25000,
    }).catch(() => {});

    // After networkidle, try to grab token from window
    await _page.evaluate(() => window.__xct).then(tok => {
      if (tok) { _token = tok; _tokenTs = Date.now(); }
    }).catch(() => {});

    await _page.waitForTimeout(extraWait);
    clearTimeout(timeout);
    _page.off('response', handler);
    settle(null);
  });
}

// ══════════════════════════════════════════════════════════════════
//  Public API
// ══════════════════════════════════════════════════════════════════

async function fetchSeriesList(page = 1, size = 50) {
  // Primary: capture response via navigation (most reliable, no token needed for capture)
  const nav = await captureViaNav(
    `series-list?leagueId=${LEAGUE_ID}`,
    'series/list'
  );
  if (nav?.data) return nav.data;
  if (Array.isArray(nav)) return nav;

  // Fallback: direct API call with captured token
  await ensureBrowser();
  const data = await directCall('series/list', { leagueId: LEAGUE_ID, page, size });
  return data?.data ?? data;
}

async function fetchPointsTable(seriesId) {
  await ensureBrowser();

  // If we already have a fresh token, go straight to directCall — much faster.
  // CricClubs always fires a default (wrong-seriesId) getPointsTable on page load,
  // so captureViaNav never yields the right data; directCall with a fresh token works reliably.
  if (tokenFresh()) {
    const data = await directCall('team/getPointsTable', {
      clubId: LEAGUE_ID, seriesId,
    }).catch(e => { console.warn('  ⚠️  directCall getPointsTable failed:', e.message); return null; });
    if (data?.data) return data.data;
    if (Array.isArray(data)) return data;
  }

  // Token stale — navigate to refresh it, then directCall with the fresh token.
  // (We still do captureViaNav with the seriesId filter as a bonus attempt,
  //  but we expect it to miss and fall through to directCall.)
  console.log(`  🔄 Token stale for ${seriesId}, navigating to refresh…`);
  const nav = await captureViaNav(
    `points-table?seriesId=${seriesId}`,
    'getPointsTable',
    500,          // short extraWait — we don't expect a match
    seriesId
  );
  if (nav?.data) return nav.data;
  if (Array.isArray(nav)) return nav;

  console.log(`  ↩️  Nav miss for ${seriesId}, trying directCall with refreshed token…`);
  const fallback = await directCall('team/getPointsTable', {
    clubId: LEAGUE_ID, seriesId,
  }).catch(e => { console.warn('  ⚠️  directCall getPointsTable failed:', e.message); return null; });
  if (fallback?.data) return fallback.data;
  if (Array.isArray(fallback)) return fallback;

  console.warn(`  ⚠️  No points table data for ${seriesId}`);
  return [];
}

async function fetchMatchList(seriesId) {
  // Uses the real match list API: series/{seriesId}/matches?leagueId=...
  // Routes through directCall for consistent headers + token-refresh retry logic.
  // Use a large size to get all matches in one call (default page size is only 30).
  const data = await directCall(`series/${seriesId}/matches`, {
    leagueId: LEAGUE_ID,
    size: 1000,
    page: 1,
  });
  return data?.data ?? data ?? {};
}

async function fetchPlayerStats(seriesId) {
  await ensureBrowser();
  const data = await directCall('stats/getPlayerStats', {
    clubId: LEAGUE_ID, seriesId,
  }).catch(() => null);
  return data?.data ?? {};
}

async function closeBrowser() {
  await _browser?.close().catch(() => {});
}

async function fetchSeriesRules(seriesId) {
  // Returns the points system for a series: winPoints, lossPoints, tiePoints, abandonedPoints
  const data = await directCall(`league/${LEAGUE_ID}/series/${seriesId}/details`, {});
  const d = data?.data ?? {};
  return {
    winPoints:             d.winPoints             ?? 2,
    lossPoints:            d.lossPoints            ?? 0,
    tiePoints:             d.tiePoints             ?? 1,
    abandonedPoints:       d.abandonedPoints       ?? 1,
    bonusPoints:           d.bonusPoints           ?? 0,
    superLeagueBonusPoints:d.superLeagueBonusPoints ?? 0,
  };
}

async function fetchTeamMatches(seriesId, teamId, year) {
  // Returns per-match data for one team including selectedTeamPoints (exact pts inc. bonus)
  const data = await directCall(`series/${seriesId}/matches`, {
    leagueId: LEAGUE_ID,
    teamId,
    status: 'All',
    year: year ?? new Date().getFullYear(),
    size: 1000,
    page: 1,
  });
  return data?.data ?? data ?? {};
}

async function fetchFixtureDetails(fixtureId) {
  // Try to get per-match points / scorecard data
  const data = await directCall(`fixture/${fixtureId}/details`, {}).catch(() => null)
            ?? await directCall(`match/${fixtureId}`, {}).catch(() => null)
            ?? await directCall(`fixture/${fixtureId}`, {}).catch(() => null);
  return data;
}

module.exports = {
  fetchSeriesList,
  fetchPointsTable,
  fetchMatchList,
  fetchTeamMatches,
  fetchSeriesRules,
  fetchPlayerStats,
  fetchFixtureDetails,
  ensureBrowser,
  closeBrowser,
  LEAGUE_ID,
};
